version: "3.7" 
services: 
  mongo_db: 
    build: ./mongodb 
    ports: 
      - "27017:27017"
      
  
  backend: 
    build: ./backend_api 
    ports: 
      - "8000:8000" 

  frontend: 
    build: ./frontend 
    ports: 
      - "3000:3000"