apiVersion: v1
kind: Service
metadata:
  namespace: seng-trade-app
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.network/net-10.9.0.0: "true"
    io.kompose.service: trigger-service
  name: trigger-service
spec:
  clusterIP: 10.9.0.12
  type: ClusterIP
  selector:
    io.kompose.service: trigger-service
status:
  loadBalancer: {}