apiVersion: v1
kind: Service
metadata:
  namespace: seng-trade-app
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.network/net-10.9.0.0: "true"
    io.kompose.service: frontend
  name: frontend
spec:
  clusterIP: 10.9.0.5
  type: ClusterIP
  ports:
    - name: frontend-port
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
