apiVersion: v1
kind: Service
metadata:
  namespace: seng-trade-app
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.network/net-10.9.0.0: "true"
    io.kompose.service: quote-server
  name: quote-server
spec:
  clusterIP: 10.9.0.6
  type: ClusterIP
  ports:
    - name: quote-serv-port
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: quote-server
status:
  loadBalancer: {}
