apiVersion: v1
kind: Service
metadata:
  namespace: seng-trade-app
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.network/net-10.9.0.0: "true"
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  clusterIP: 10.9.0.15
  type: ClusterIP
  ports:
    - name: rabbit-port1
      port: 5672
      targetPort: 5672
    - name: rabbit-port2
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
