version: "3.5"
services:
  backend:
    container_name: backend
    image: quay.io/stockapp/backend:latest
    ports:
      - target: 8000
        published: 8094
  backend-api:
    container_name: backend-api
    image: quay.io/stockapp/backend-api:latest
    ports:
      - target: 8080
        published: 8088
      - target: 8000
        published: 8089
  frontend:
    container_name: frontend
    image: quay.io/stockapp/frontend:latest
    ports:
      - target: 3000
        published: 8087
  log-service:
    container_name: log-service
    image: quay.io/stockapp/log-service:latest
    ports:
      - target: 8080
        published: 8083
      - target: 8004
        published: 8084
  m:
    container_name: m
    image: quay.io/stockapp/m:latest
    ports:
      - target: 8080
        published: 8090
  mongo-db:
    container_name: mongo-db
    image: quay.io/stockapp/mongo-db:latest
    ports:
      - target: 27017
        published: 8080
  queue-service:
    container_name: queue-service
    image: quay.io/stockapp/queue-service:latest
    ports:
      - target: 8080
        published: 8093
  quote-cache:
    container_name: quote-cache
    image: quay.io/stockapp/quote-cache:latest
    ports:
      - target: 6379
        published: 8082
  quote-server:
    container_name: quote-server
    image: quay.io/stockapp/quote-server:latest
    ports:
      - target: 8080
        published: 8091
      - target: 8002
        published: 8092
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.17-management-alpine
    ports:
      - target: 5672
        published: 8085
      - target: 15672
        published: 8086
  redis-cache:
    container_name: redis-cache
    image: quay.io/stockapp/redis-cache:latest
    ports:
      - target: 8080
        published: 8095
      - target: 6379
        published: 8096
  worker:
    container_name: worker
    image: quay.io/stockapp/worker:latest
    ports:
      - target: 8003
        published: 8081
  worker-service:
    container_name: worker-service
    image: quay.io/stockapp/worker-service:latest
    ports:
      - target: 8080
        published: 8097
      - target: 8003
        published: 8098
