patches:
  - path: apps-v1-deployment-quote-cache.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: quote-cache
  - path: apps-v1-deployment-frontend.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
  - path: apps-v1-deployment-queue-service.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: queue-service
  - path: apps-v1-deployment-quote-server.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: quote-server
  - path: apps-v1-deployment-m.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: m
  - path: apps-v1-deployment-backend-api.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: backend-api
  - path: apps-v1-deployment-worker-service.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: worker-service
  - path: apps-v1-deployment-mongo-db.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: mongo-db
  - path: apps-v1-deployment-log-service.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: log-service
  - path: apps-v1-deployment-redis-cache.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: redis-cache
  - path: apps-v1-deployment-backend.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
  - path: apps-v1-deployment-rabbitmq.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: rabbitmq
  - path: apps-v1-deployment-worker.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: worker
resources:
  - ../../base
