apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: m
  name: m
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/stockapp/m:latest
          imagePullPolicy: Always
          name: m
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: quay-io-imagepullsecret
      restartPolicy: Always
      securityContext: {}
status: {}
