apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: mongo-db
  name: mongo-db
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/stockapp/mongo-db:latest
          imagePullPolicy: Always
          name: mongo-db
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: quay-io-imagepullsecret
      restartPolicy: Always
      securityContext: {}
status: {}
