apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: quote-cache
  name: quote-cache
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/stockapp/quote-cache:latest
          imagePullPolicy: Always
          name: quote-cache
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: quay-io-imagepullsecret
      restartPolicy: Always
      securityContext: {}
status: {}
