
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: log-service
    name: log-service
spec:
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ports:
        - name: port-8004
          port: 8004
          protocol: TCP
          targetPort: 8004
        - name: port-8080
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        move2kube.konveyor.io/service: log-service
    sessionAffinity: None
    type: NodePort
status:
    loadBalancer: {}

...
