
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: rabbitmq
    name: rabbitmq
spec:
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ports:
        - name: port-5672
          port: 5672
          protocol: TCP
          targetPort: 5672
        - name: port-15672
          port: 15672
          protocol: TCP
          targetPort: 15672
    selector:
        move2kube.konveyor.io/service: rabbitmq
    sessionAffinity: None
    type: NodePort
status:
    loadBalancer: {}

...
