apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJaSGxzWVc1cWEyVnRjQ3R6ZEc5amEyRndjSE5sYm1jME5qZzZNRVZMUVVkSU5VeFNPRmswUVVkTFVsVTRTemRZU1ZZd1ZVdEVNekE1VFV3MFZqVk9PRk15VnpOWFJUVTVUVmRET0ZwVFJGZE5VVXBGVVZVMVZqWlJVQT09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: quay-io-imagepullsecret
type: kubernetes.io/dockerconfigjson
