
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: backend
    name: backend
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/stockapp/backend:latest
                  imagePullPolicy: Always
                  name: backend
                  ports:
                    - containerPort: 8000
                      protocol: TCP
                  resources: {}
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
status: {}

...
