
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: rabbitmq
    name: rabbitmq
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: rabbitmq:3.8.17-management-alpine
                  imagePullPolicy: Always
                  livenessProbe:
                    exec:
                        command:
                            - nc
                            - -z
                            - localhost
                            - "5672"
                    failureThreshold: 5
                    periodSeconds: 10
                    timeoutSeconds: 5
                  name: rabbitmq
                  ports:
                    - containerPort: 5672
                      protocol: TCP
                    - containerPort: 15672
                      protocol: TCP
                  resources: {}
            restartPolicy: Always
            securityContext: {}
status: {}

...
