version: '3.9'
name: stock-trader-app
services:
  kube-cluster:
    #privileged: true
    image: kube-cluster
    environment:
      LOCAL_WORKSPACE_FOLDER: /home/birdy/output2/sengA2468
      localWorkspaceFolder: /home/birdy/output2/sengA2468
      SYNC_LOCALHOST_KUBECONFIG: "true"
      #KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      COMPOSE_PROJECT_NAME: stock-trader-app

    init: true
    user: kube-trader
    build: 
      context: .
      dockerfile: Dockerfile
    #working_dir: /tmp
    volumes:
      # Forwards the local Docker socket to the container.
      - "/var/run/docker.sock:/var/run/docker-host.sock"
      # Update this to wherever you want VS Code to mount the folder of your project
      - "../..:/workspaces:cached"
      - "./${LOCAL_WORKSPACE_FOLDER:-./}:/workspace"
      - "../devcontainer:/workspace/"
      - type: bind
        source: ${HOME}${USERPROFILE}/.kube
        target: /usr/local/share/kube-localhost
      - type: bind
        source: ${HOME}${USERPROFILE}/.minikube
        target: /usr/local/share/minikube-localhost
    container_name: launch-container
    env_file: .env
    labels:
      com.sengstockapp.project: "${COMPOSE_PROJECT_NAME}"
      com.sengstockapp.service: kube-cluster

    restart: on-failure
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
    - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    #$"${localWorkspaceFolder}"