apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: stockapp-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      creationTimestamp: null
      name: stockapp-deploy
      namespace: argocd
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: ""
      source:
        path: '<TODO: fill in the path to the folder containing the K8s yamls>'
        repoURL: '<TODO: fill in the git/helm repo url>'
    status:
      health: {}
      summary: {}
      sync:
        comparedTo:
          destination: {}
          source:
            repoURL: ""
        status: ""
parameters: []
