apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: stockapp-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: backend-api
      name: backend-api
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/backend-api:latest
              imagePullPolicy: Always
              name: backend-api
              ports:
                - containerPort: 8080
                - containerPort: 8000
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: backend
      name: backend
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/backend:latest
              imagePullPolicy: Always
              name: backend
              ports:
                - containerPort: 8000
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: frontend
      name: frontend
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/frontend:latest
              imagePullPolicy: Always
              name: frontend
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: log-service
      name: log-service
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/log-service:latest
              imagePullPolicy: Always
              name: log-service
              ports:
                - containerPort: 8080
                - containerPort: 8004
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: queue-service
      name: queue-service
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/queue-service:latest
              imagePullPolicy: Always
              name: queue-service
              ports:
                - containerPort: 8080
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: quote-cache
      name: quote-cache
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/quote-cache:latest
              imagePullPolicy: Always
              name: quote-cache
              ports:
                - containerPort: 6379
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: m
      name: m
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/m:latest
              imagePullPolicy: Always
              name: m
              ports:
                - containerPort: 8080
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: mongo-db
      name: mongo-db
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/mongo-db:latest
              imagePullPolicy: Always
              name: mongo-db
              ports:
                - containerPort: 27017
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: quote-server
      name: quote-server
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/quote-server:latest
              imagePullPolicy: Always
              name: quote-server
              ports:
                - containerPort: 8080
                - containerPort: 8002
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: rabbitmq
      name: rabbitmq
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: rabbitmq:3.8.17-management-alpine
              imagePullPolicy: Always
              livenessProbe:
                exec:
                  command:
                    - nc
                    - -z
                    - localhost
                    - "5672"
                failureThreshold: 5
                periodSeconds: 10
                timeoutSeconds: 5
              name: rabbitmq
              ports:
                - containerPort: 5672
                  protocol: TCP
                - containerPort: 15672
                  protocol: TCP
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: redis-cache
      name: redis-cache
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/redis-cache:latest
              imagePullPolicy: Always
              name: redis-cache
              ports:
                - containerPort: 8080
                - containerPort: 6379
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: worker-service
      name: worker-service
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/worker-service:latest
              imagePullPolicy: Always
              name: worker-service
              ports:
                - containerPort: 8080
                - containerPort: 8003
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: worker
      name: worker
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/stockapp/worker:latest
              imagePullPolicy: Always
              name: worker
              ports:
                - containerPort: 8003
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
