apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: backend
  name: backend
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: port-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    move2kube.konveyor.io/service: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
