apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: frontend
  name: frontend
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: port-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    move2kube.konveyor.io/service: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
