apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: mongo-db
  name: mongo-db
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: port-27017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    move2kube.konveyor.io/service: mongo-db
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
