apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: redis-cache
  name: redis-cache
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: port-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-6379
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    move2kube.konveyor.io/service: redis-cache
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
