
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: quote-server
    name: quote-server
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/stockapp/quote-server:latest
                  imagePullPolicy: Always
                  name: quote-server
                  ports:
                    - containerPort: 8080
                    - containerPort: 8002
                      protocol: TCP
                  resources: {}
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
status: {}

...
