apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: stockapp-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: stockapp
      name: stockapp
    spec:
      rules:
        - host: stockapp.com
          http:
            paths:
              - backend:
                  service:
                    name: el-stockapp-git-repo
                    port:
                      name: port-8080
                path: /el-stockapp-git-repo
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerTemplate
    metadata:
      creationTimestamp: null
      name: stockapp-run-clone-build-push
    spec:
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            creationTimestamp: null
            name: stockapp-clone-build-push-$(uid)
          spec:
            params:
              - name: image-registry-url
                value: quay.io/stockapp
            pipelineRef:
              name: stockapp-clone-build-push
            serviceAccountName: stockapp-clone-push
            workspaces:
              - name: stockapp-shared-data
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    storageClassName: default
                  status: {}
          status: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: null
      name: stockapp-tekton-triggers-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: stockapp-tekton-triggers-admin
    subjects:
      - kind: ServiceAccount
        name: stockapp-tekton-triggers-admin
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      creationTimestamp: null
      name: stockapp-clone-build-push
    spec:
      params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
      tasks:
        - name: clone-1
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/backend-api
            - name: DOCKERFILE
              value: backend_api/Dockerfile
            - name: CONTEXT
              value: backend_api
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-2
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-1
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-2
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/log-service:latest
            - name: DOCKERFILE
              value: log_service/Dockerfile
            - name: CONTEXT
              value: log_service
          runAfter:
            - clone-2
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-3
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-2
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-3
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/quote-server:latest
            - name: DOCKERFILE
              value: quote_server/Dockerfile
            - name: CONTEXT
              value: quote_server
          runAfter:
            - clone-3
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-4
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-3
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-4
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/quote-cache:latest
            - name: DOCKERFILE
              value: quote_cache/Dockerfile
            - name: CONTEXT
              value: quote_cache
          runAfter:
            - clone-4
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-5
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-4
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-5
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/backend:latest
            - name: DOCKERFILE
              value: backend_api/Dockerfile
            - name: CONTEXT
              value: backend_api
          runAfter:
            - clone-5
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-6
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-5
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-6
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/mongo-db:latest
            - name: DOCKERFILE
              value: mongodb/Dockerfile
            - name: CONTEXT
              value: mongodb
          runAfter:
            - clone-6
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-7
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-6
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-7
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/frontend:latest
            - name: DOCKERFILE
              value: frontend/Dockerfile
            - name: CONTEXT
              value: frontend
          runAfter:
            - clone-7
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-8
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-7
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-8
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/quote-server
            - name: DOCKERFILE
              value: quote_server/Dockerfile
            - name: CONTEXT
              value: quote_server
          runAfter:
            - clone-8
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-9
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-8
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-9
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/queue-service
            - name: DOCKERFILE
              value: queue_service/Dockerfile
            - name: CONTEXT
              value: queue_service
          runAfter:
            - clone-9
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-10
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-9
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-10
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/redis-cache
            - name: DOCKERFILE
              value: quote_cache/Dockerfile
            - name: CONTEXT
              value: quote_cache
          runAfter:
            - clone-10
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-11
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-10
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-11
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/worker-service
            - name: DOCKERFILE
              value: worker_service/Dockerfile
            - name: CONTEXT
              value: worker_service
          runAfter:
            - clone-11
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-12
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-11
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-12
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/worker:latest
            - name: DOCKERFILE
              value: worker_service/Dockerfile
            - name: CONTEXT
              value: worker_service
          runAfter:
            - clone-12
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-13
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-12
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-13
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/m
            - name: DOCKERFILE
              value: cli_app/Dockerfile
            - name: CONTEXT
              value: cli_app
          runAfter:
            - clone-13
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
        - name: clone-14
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-13
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: stockapp-shared-data
        - name: build-push-14
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/log-service
            - name: DOCKERFILE
              value: log_service/Dockerfile
            - name: CONTEXT
              value: log_service
          runAfter:
            - clone-14
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: stockapp-shared-data
      workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: stockapp-shared-data
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: stockapp-clone-push
    secrets:
      - name: stockapp-image-registry
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerBinding
    metadata:
      creationTimestamp: null
      name: stockapp-git-event
    spec: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: stockapp-tekton-triggers-admin
    rules:
      - apiGroups:
          - triggers.tekton.dev
        resources:
          - eventlisteners
          - triggerbindings
          - triggertemplates
        verbs:
          - get
      - apiGroups:
          - tekton.dev
        resources:
          - pipelineruns
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: stockapp-tekton-triggers-admin
  - apiVersion: v1
    data:
      .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJaSGxzWVc1cWEyVnRjQ3R6ZEc5amEyRndjSE5sYm1jME5qZzZNRVZMUVVkSU5VeFNPRmswUVVkTFVsVTRTemRZU1ZZd1ZVdEVNekE1VFV3MFZqVk9PRk15VnpOWFJUVTVUVmRET0ZwVFJGZE5VVXBGVVZVMVZqWlJVQT09IgoJCX0KCX0KfQ==
    kind: Secret
    metadata:
      creationTimestamp: null
      name: quay-io-imagepullsecret
    type: kubernetes.io/dockerconfigjson
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: EventListener
    metadata:
      creationTimestamp: null
      name: stockapp-git-repo
    spec:
      namespaceSelector: {}
      resources: {}
      serviceAccountName: stockapp-tekton-triggers-admin
      triggers:
        - bindings:
            - ref: stockapp-git-event
          template:
            ref: stockapp-run-clone-build-push
    status:
      configuration:
        generatedName: ""
  - apiVersion: v1
    data:
      .dockerconfigjson: PFRPRE86IGluc2VydCB5b3VyIGRvY2tlciBjb25maWcganNvbj4=
    kind: Secret
    metadata:
      annotations:
        tekton.dev/docker-0: ""
      creationTimestamp: null
      name: stockapp-image-registry
    type: kubernetes.io/dockerconfigjson
parameters: []
